CREATE TABLE MATERIA_PRIMA (
 COD_MATERIA_PRIMA NUMBER CONSTRAINT PK_MATPRI_CODMATPRI PRIMARY KEY,
 MATERIA_PRIMA VARCHAR2(20) CONSTRAINT UK_MATPRI_MATPRI UNIQUE
);

CREATE TABLE CATEGORIA (
 COD_CATEGORIA NUMBER CONSTRAINT PK_CAT_CODCAT PRIMARY KEY,
 CATEGORIA VARCHAR2(20) CONSTRAINT UK_CAT_CAT UNIQUE CONSTRAINT CK_CAT_CAT CHECK(CATEGORIA IN('DOCE','BEBIDA','CONGELADO'))
);

CREATE TABLE PRODUTO (
 COD_PRODUTO NUMBER CONSTRAINT PK_PRO_CODPRO PRIMARY KEY,
 COD_CATEGORIA NUMBER CONSTRAINT FK_PRODUTO_CATEGORIA REFERENCES CATEGORIA(COD_CATEGORIA),
 PRODUTO VARCHAR2(20) CONSTRAINT UK_PRO_PRO UNIQUE
);


CREATE TABLE ITEM_PRODUTO (
 COD_PRODUTO NUMBER,
 COD_MATERIA_PRIMA NUMBER,
 QUANTIDADE NUMBER CONSTRAINT NN_ITEPRO_QDE NOT NULL,
 CONSTRAINT PK_ITEPRO_CODPRO_COD_MAT PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA),
 CONSTRAINT FK_ITEPRO_CODPRO
 FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
 CONSTRAINT FK_ITEPRO_CODMATPRI
 FOREIGN KEY (COD_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA(COD_MATERIA_PRIMA)
);
