SELECT * FROM DB_FUNCIONARIO df 


SELECT
	dd.NM_DEPTO AS DEPARTAMENTO,
	ROUND(AVG(df.VL_SALARIO_BRUTO), 2) AS MEDIA_SALARIO
FROM DB_FUNCIONARIO df 
INNER JOIN DB_DEPTO dd 
	ON df.CD_DEPTO  = dd.CD_DEPTO 
GROUP BY dd.NM_DEPTO 

SELECT 
	dd.NM_DEPTO AS DEPARTAMENTO,
	SUM(df.VL_SALARIO_BRUTO) AS SOMA_FOLHA_PGTO
FROM DB_FUNCIONARIO df 
INNER JOIN DB_DEPTO dd 
	ON DF.CD_DEPTO = DD.CD_DEPTO 
GROUP BY DD.NM_DEPTO 
ORDER BY 2 DESC 

SELECT COUNT(DF.CD_FUNCIONARIO) AS QUANTIDADE_GERENTES
FROM DB_FUNCIONARIO df 
WHERE DF.DS_CARGO LIKE '%gerente%'

SELECT
	DD.NM_DEPTO,
	COUNT(DF.CD_FUNCIONARIO) 
FROM DB_FUNCIONARIO df 
INNER JOIN DB_DEPTO dd 
	ON DF.CD_DEPTO = DD.CD_DEPTO
WHERE DD.NM_DEPTO LIKE '%vendas%'
GROUP BY DD.NM_DEPTO

--VIEWS CONSULTAS ARMAZENADAS

CREATE VIEW VW_RELATORIO_VENDEDOR
AS
SELECT 
	df.NM_FUNCIONARIO AS VENDEDOR,
	DF.DT_NASCIMENTO AS DATA_NASCIMENTO,
	DF.VL_SALARIO_BRUTO AS SALARIO_BRUTO,
	DD.NM_DEPTO AS DEPARTAMENTO,
	DF2.NM_FUNCIONARIO AS GERENTE,
	COUNT(DP.NR_PEDIDO) AS QUANTIDADE_VENDAS
FROM DB_FUNCIONARIO df 
INNER JOIN DB_DEPTO dd 
	ON DF.CD_DEPTO = DD.CD_DEPTO 
INNER JOIN DB_FUNCIONARIO df2 
	ON DF.CD_GERENTE = DF2.CD_FUNCIONARIO
INNER JOIN DB_PEDIDO dp 
	ON DP.CD_FUNC_ATD = DF.CD_FUNCIONARIO
WHERE DF.DS_CARGO LIKE '%Vend%'
GROUP BY df.NM_FUNCIONARIO,
	DF.DT_NASCIMENTO,
	DF.VL_SALARIO_BRUTO,
	DD.NM_DEPTO,
	DF2.NM_FUNCIONARIO
;

SELECT * FROM VW_RELATORIO_VENDEDOR 
WHERE QUANTIDADE_VENDAS > 500