--qt usuarios ativos
SELECT * FROM DB_FUNCIONARIO df 
WHERE DF.ST_FUNC = 'A'

SELECT COUNT(DF.CD_FUNCIONARIO) QUANTIDADE_ATIVOS
FROM DB_FUNCIONARIO df 
WHERE DF.ST_FUNC = 'A'

--AT ATIVOS POR NOME DPTO
SELECT 
	DD.NM_DEPTO,
	COUNT(DF.CD_FUNCIONARIO) QUANTIDADE_ATIVOS
FROM DB_FUNCIONARIO df 
INNER JOIN DB_DEPTO dd ON DF.CD_DEPTO AS
WHERE DF.ST_FUNC = 'A'

--QT PEDIDOS NO MES
SELECT TO_CHAR(DP.DT_PEDIDO, 'YYYY-MM'),
	COUNT(DP.NR_PEDIDO) AS QUANTIDADE_PEDIDOS,
	SUM(DP.VL_TOT_PEDIDO) AS VALOR_TOTAL_VENDAS
FROM DB_PEDIDO dp 
GROUP BY TO_CHAR(DP.DT_PEDIDO, 'YYYY-MM')
ORDER BY TO_CHAR(DP.DT_PEDIDO, 'YYYY-MM')

--CLIENTES QUE FIZERAM MAIS QUE 5 COMPRAS
SELECT 
	DC.NM_CLIENTE,
	COUNT(DP.NR_PEDIDO) 
FROM DB_PEDIDO dp 
INNER JOIN DB_CLIENTE dc 
	ON DP.NR_PEDIDO = DC.NR_CLIENTE
GROUP BY DC.NM_CLIENTE 
HAVING COUNT(DP.NR_PEDIDO) > 5
ORDER BY 2


	