--JOINS
SELECT * FROM DB_FUNCIONARIO df 

SELECT * FROM DB_DEPTO dd 

SELECT * FROM 

--INNER JOIN EX 1
SELECT DF.CD_FUNCIONARIO, DF.NM_FUNCIONARIO AS NOME, DF.DT_NASCIMENTO, DD.CD_DEPTO 
FROM DB_FUNCIONARIO df 
INNER JOIN DB_DEPTO dd 
	ON DF.CD_DEPTO = DD.CD_DEPTO 

--LEFT JOIN EX 2
SELECT DF.CD_FUNCIONARIO ,
	DF.NM_FUNCIONARIO ,
	D1.NM_LOGRADOURO,
	D1.NR_CEP,
	DB.NM_BAIRRO,
	DC.NM_CIDADE,
	DE.NM_ESTADO
FROM DB_FUNCIONARIO df 
LEFT JOIN DB_END_FUNC def 
	ON DF.CD_FUNCIONARIO = DEF.CD_FUNCIONARIO 
LEFT JOIN DB_LOGRADOURO dl 
	ON D1.CD_LOGRADOURO = DEF.CD_LOGRADOURO 
LEFT JOIN DB_BAIRRO db 
	ON DB.CD_BAIRRO = D1.CD_BAIRRO 
LEFT JOIN DB_CIDADE dc 
	ON DB.CD_CIDADE = DB.CD_CIDADE 
LEFT JOIN DB_ESTADO de 
	ON DE.SG_ESTADO = DC.SG_ESTADO 

--INNER JOIN EX 3
SELECT DP.NR_PEDIDO, DF.NM_FUNCIONARIO AS NOME_MOTOBOY, DC.NM_CLIENTE AS NOMECLIENTE FROM DB_PEDIDO dp 
INNER JOIN DB_FUNCIONARIO df 
	ON DP.CD_FUNC_MOTOBOY = DF.CD_FUNCIONARIO 
INNER JOIN DB_CLIENTE dc 
	ON DP.NR_CLIENTE = DC.NR_CLIENTE 
WHERE EXTRACT(YEAR FROM DP.DT_PEDIDO) = 2019
ORDER BY DP.NR_PEDIDO

-- INNER JOIN EX 4
SELECT DP.NR_PEDIDO,
	DP.DT_PEDIDO,
	DP.DT_PREV_ENTREGA 
FROM DB_PEDIDO dp 
INNER JOIN DB_FUNCIONARIO df 
 ON DP.CD_FUNC_ATD = DF.CD_FUNCIONARIO 
WHERE DF.NM_FUNCIONARIO LIKE 'Raina%'
ORDER BY dp.DT_PEDIDO DESC 