UPDATE DB_FUNCIONARIO SET VL_SALARIO_BRUTO = 20000.75 WHERE CD_FUNCIONARIO = 0

SELECT NM_FUNCIONARIO, VL_SALARIO_BRUTO, ROUND(555999.688, 2)  FROM DB_FUNCIONARIO df WHERE CD_FUNCIONARIO = 0 --ROUND FAZ O ARREDONDAMENTO, APÓS A VIRGULA O NÚMERO DE CASAS DECIMAIS

SELECT NM_FUNCIONARIO, VL_SALARIO_BRUTO, ROUND(VL_SALARIO_BRUTO, 1)  FROM DB_FUNCIONARIO df WHERE CD_FUNCIONARIO = 0

SELECT ROUND(889955.68745, 2) FROM DUAL --ROUND EM TABELA VIRTUAL 


--ROUND FUNÇÃO QUE ARREDONDA UM VALOR 
--MOD FUNÇÃO O RESTO DE UMA OPERAÇÃO DE DIVISÃO
--ABS VALOR ABSOLUTO IGNORA POSIRTVOS E NEGATIVOS
--SQRT RETORNA RAIZ QUADRADA
--FLOOR ARRENDONDAMENTO DE NUMEROS DECIMAIS PARA BAIXO
--CEIL ARRENDONDAMENTO DE NUMEROS DECIMAIS PARA CIMA

SELECT 
	ROUND(VL_SALARIO_BRUTO, 4) FUNC_ROUND,
	MOD(VL_SALARIO_BRUTO, 2) FUNC_MOD,
	TRUNC(VL_SALARIO_BRUTO, 0) FUNC_TRUC,
	ABS(VL_SALARIO_BRUTO * (-1)) FUNC ABS,
	SQRT(VL_SALARIO_BRUTO) FUNC_SQRT,
	FLOOR(VL_SALARIO_BRUTO) FUNC_FLOOR,
	CEIL(VL_SALARIO_BRUTO) FUNC_CEIL 
FROM DB_FUNCIONARIO df 

SELECT NM_FUNCIONARIO, UPPER(NM_FUNCIONARIO),  DS_CARGO FROM DB_FUNCIONARIO df --UPPER CONVERTE TODO O TEXTO PARA MAIUSCULO

SELECT NM_FUNCIONARIO, UPPER('Teste'),  DS_CARGO FROM DB_FUNCIONARIO df

SELECT NM_FUNCIONARIO, UPPER(NM_FUNCIONARIO), LOWER(DS_CARGO) AS CARGO_MINISC FROM DB_FUNCIONARIO df --LOWER CONVERTE TODO O TEXTO PARA MINUSC.

SELECT NM_FUNCIONARIO, UPPER(NM_FUNCIONARIO), LOWER(DS_CARGO) AS CARGO_MINISC, CONCAT(NM_FUNCIONARIO, DS_CARGO)  FROM DB_FUNCIONARIO df --CONCATENACAO DE DOIS CAMPOS

--CONCAT CONCATENA DOIS VALORES RETORNANDO RESULTADO UNICO
--LENGTH RETORNA A QUANTIDADE DE CARACTERES 
--LPAD / RPAD PREENCHE O CAMPO COM CARACTERES A DIREITA OU A ESQUERDA 
-- LTRIM / RTRIM ELIMINA CARACTERES EM BRANCO A ESQUERDA OU A DIREITA 
--TRIM ELIMINA CARACTERES EM BRANCO DA ESQUERDA E DIREITA 
--REPLACE SUBSTITUI TODOS OS CARACTERES POR OUTROS 
--INSTR PESQUISA SE TEM UMA STRING SOBRE A OUTRA

SELECT 
	CONCAT(NM_FUNCIONARIO, NM_FUNCIONARIO),
	CONCAT(NM_FUNCIONARIO, '_TESTE'),
	SUBSTR(NM_FUNCIONARIO, 1, 3),
	SUBSTR(NM_FUNCIONARIO, 3),
	LENGTH(NM_FUNCIONARIO)
FROM DB_FUNCIONARIO df  

SELECT 
	NM_FUNCIONARIO,
	INSTR(NM_FUNCIONARIO, 'A'),
	INSTR(NM_FUNCIONARIO, 'A', 3),
	INSTR(NM_FUNCIONARIO, 'A', 3, 2)	
FROM DB_FUNCIONARIO df  

SELECT 
	NM_FUNCIONARIO,
	REPLACE(NM_FUNCIONARIO, 'A', '*')
FROM DB_FUNCIONARIO df 

--TO_CHAR CONVERT QUALQUER TIPO DE DADO PARA TEXTO 
--TO_NUMBER CONVERT QUALQUER TIPO DE DADO PARA NUMERO
--TO_DATE CONVERT QUALQUER TIPO DE DADO PARA DATA

SELECT 
	1234 NUMERO,
	TO_CHAR(1234, '$99999'),
	TO_CHAR(1234, '$9999,999'),
	TO_CHAR(1234, '$9999.99')
FROM DUAL;

SELECT 
	CURRENT_DATE DATA_DUAL,
	TO_CHAR(CURRENT_DATE, 'DD'),
	TO_CHAR(CURRENT_DATE, 'DY'),
	TO_CHAR(CURRENT_DATE, 'DAY'),
	TO_CHAR(CURRENT_DATE, 'MONTH'),
	TO_CHAR(CURRENT_DATE, 'HH:MI:SS')
FROM DUAL;

SELECT 
	MAX(VL_TOT_PEDIDO)
FROM DB_PEDIDO dp 

--CRIANDO FUNCOES
CREATE FUNCTION get_max_price 
	RETURN NUMBER --VARCHAR 
	IS max_price NUMBER(10, 2); --DECLARANDO VARIAVEL EM ORACLE
	BEGIN 
		SELECT MAX(VL_TOT_PEDIDO)
		INTO max_price 
		FROM DB_PEDIDO dp;
		RETURN (max_price); --SEMPRE ULTIMA LINHA DE UMA FUNCTION
	END;

SELECT 
	NR_PEDIDO,
	VL_TOT_PEDIDO,
	get_max_price AS maximo_valor
FROM DB_PEDIDO dp 

SELECT VL_UNITARIO FROM DB_PRODUTO dp WHERE CD_PRODUTO = 'LN001'

CREATE FUNCTION get_price_product(prd_no IN VARCHAR)
	RETURN NUMBER 
	IS prd_price NUMBER(8,2);
	BEGIN 
		SELECT VL_UNITARIO 
		INTO prd_price 
		FROM DB_PRODUTO dp 
		WHERE CD_PRODUTO = prd_no;
		RETURN (prd_price);
	END;

SELECT get_price_product('LN005') FROM DUAL 
