SELECT * FROM DB_FUNCIONARIO df 

UPDATE DB_FUNCIONARIO SET NM_FUNCIONARIO = 'isís barcelos toscano' WHERE CD_FUNCIONARIO = 0

--SELECT NOME FUNC COM SOMENTE INICIAIS EM MAIUSCULO
SELECT 
	NM_FUNCIONARIO,
	INITCAP(NM_FUNCIONARIO)
FROM DB_FUNCIONARIO df 

--SELECT NOME FUNCS, DATA DE NSC E CALCULAR IDADE EM ANOS
SELECT 
	NM_FUNCIONARIO,
	DT_NASCIMENTO,
	TRUNC(MONTHS_BETWEEN(CURRENT_DATE, DT_NASCIMENTO) / 12) IDADE
FROM DB_FUNCIONARIO df 

--INFORMAR IDADE DE FUNC PAR OU IMPAR
SELECT 
	NM_FUNCIONARIO,
	DT_NASCIMENTO,
	TRUNC(MONTHS_BETWEEN(CURRENT_DATE, DT_NASCIMENTO) / 12) IDADE,
	CASE
		WHEN MOD(TRUNC(MONTHS_BETWEEN(CURRENT_DATE, DT_NASCIMENTO) / 12),2) = 0 THEN 'PAR'
		WHEN MOD(TRUNC(MONTHS_BETWEEN(CURRENT_DATE, DT_NASCIMENTO) / 12),2) = 1 THEN 'IMPAR'
	END IDADE_PAR_IMPAR
FROM DB_FUNCIONARIO df 

--SELECT NOME FUNC E SALARIO CRIANDO REGRA DE ARRENDONDAMENTO SALARIAL PARA CIMA
SELECT 
	NM_FUNCIONARIO,
	VL_SALARIO_BRUTO,
	CEIL(VL_SALARIO_BRUTO) SAL_ARRED_CIMA
FROM DB_FUNCIONARIO df 

SELECT 
	NM_FUNCIONARIO,
	DT_NASCIMENTO,
	TRUNC(MONTHS_BETWEEN(CURRENT_DATE, DT_NASCIMENTO) / 12) IDADE,
	TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) IDADE_2025,
	CASE 
		WHEN TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) < 55 THEN 'NAO APOSENTADO'
		WHEN TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) >= 55 THEN 'APOSENTADO'
	END APOSENTADO,
	CASE
		WHEN TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) >= 55 THEN 0
		WHEN TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) < 55 THEN 
			55 - TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12)
	END QTD_ANOS_PARA_APOSENTAR,
	CASE 
		WHEN TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) < 55 THEN 0
		WHEN TRUNC(MONTHS_BETWEEN('31/12/2025', DT_NASCIMENTO) / 12) >= 55 THEN 
			VL_SALARIO_BRUTO * 0.7 
	END SALARIO_APOSENTADO
FROM DB_FUNCIONARIO df 