CREATE TABLE CIENTISTA (
	CODIGO INT CONSTRAINT PK_COD_CODCIENTISTA PRIMARY KEY,
	NOME VARCHAR2(50) NOT NULL, 
	DT_NASC DATE, 
	SEXO VARCHAR2(2) CONSTRAINT CK_SX_SC CHECK(SEXO IN('F','M'))
);

DROP TABLE CIENTISTA 

SELECT * FROM CIENTISTA 

INSERT INTO CIENTISTA (CODIGO, NOME, DT_NASC, SEXO) VALUES(1010, 'STEPHEN HAWKING', TO_DATE('08/01/1942', 'DD/MM/YYYY'), 'M')
INSERT INTO CIENTISTA (CODIGO, NOME, DT_NASC, SEXO) VALUES(1011, 'ALBERT EINSTEIN', TO_DATE('14/03/1879', 'DD/MM/YYYY'), 'M')
INSERT INTO CIENTISTA (CODIGO, NOME, DT_NASC, SEXO) VALUES(1012, 'ISAAC NEWTON', TO_DATE('04/01/1643', 'DD/MM/YYYY'), 'M')
INSERT INTO CIENTISTA (CODIGO, NOME, DT_NASC, SEXO) VALUES(1013, 'GALILEU GALILEI', TO_DATE('15/02/1564', 'DD/MM/YYYY'), 'M')
INSERT INTO CIENTISTA (CODIGO, NOME, DT_NASC, SEXO) VALUES(1014, 'NICOLAU COPERNICO', TO_DATE('19/02/1473', 'DD/MM/YYYY'), 'M')

CREATE TABLE CLIENTE (
	CODIGO INT,
	NOME VARCHAR2(50) NOT NULL, 
	PRIMARY KEY (CODIGO)
);


ALTER TABLE CIENTISTA 
ADD (DT_OBTO DATE)

UPDATE CIENTISTA 
 SET DT_OBTO = TO_DATE('14/03/2018', 'DD/MM/YYYY') 
 WHERE CODIGO = 1010
 
UPDATE CIENTISTA 
 SET DT_OBTO = TO_DATE('18/04/1879', 'DD/MM/YYYY') 
 WHERE CODIGO = 1011
 
UPDATE CIENTISTA 
 SET DT_OBTO = TO_DATE('31/03/1727', 'DD/MM/YYYY') 
 WHERE CODIGO = 1012

UPDATE CIENTISTA 
 SET DT_OBTO = TO_DATE('08/01/1642', 'DD/MM/YYYY') 
 WHERE CODIGO = 1013
 
UPDATE CIENTISTA 
 SET DT_OBTO = TO_DATE('24/05/1543', 'DD/MM/YYYY') 
 WHERE CODIGO = 1014
 
SELECT * FROM CIENTISTA 

UPDATE CIENTISTA 
	SET NOME = 'EINSTEIN'
	WHERE CODIGO = 1011
	
UPDATE CIENTISTA 
	SET NOME = 'NEWTON'
	WHERE CODIGO = 1012
	
SELECT * FROM CIENTISTA

ALTER TABLE CLIENTE  
ADD (DT_NASC DATE)

INSERT INTO CLIENTE (CODIGO,NOME)
	SELECT CODIGO, NOME FROM CIENTISTA 
	
SELECT * FROM CLIENTE 

UPDATE CLIENTE 
	SET DT_NASC =
	(SELECT DT_NASC FROM CIENTISTA WHERE CIENTISTA.DT_NASC = CLIENTE.DT_NASC)

SELECT * FROM CIENTISTA 
WHERE CODIGO IN (1010,1011,1012)

SELECT TO_CHAR(SYSDATE, 'MONTH')
FROM DUAL --SELECIONANDO A DATA ATUAL E TRAZENDO EM TEXTO

SELECT TO_CHAR(DT_NASC, 'MONTH')
FROM CIENTISTA 

SELECT * FROM CIENTISTA WHERE TO_CHAR(DT_NASC, 'MONTH') <> 'FEBRUARY'

	
DELETE FROM CLIENTE WHERE CODIGO NOT IN (SELECT CODIGO FROM CIENTISTA)


