SELECT * FROM EMPLOYEES --SELECAO DE TODOS OS CAMPOS DA TABELA COM *

SELECT FIRSTNAME, LASTNAME, EMAIL, JOBTITLE FROM EMPLOYEES --SELECAO FILTRADAS

SELECT FIRSTNAME AS NOME, LASTNAME AS SOBRENOME, EMAIL, JOBTITLE AS CARGO FROM EMPLOYEES --SELECAO COM ALIAS DEFINIDO

SELECT FIRSTNAME AS NOME, LASTNAME AS SOBRENOME, EMAIL, JOBTITLE AS CARGO FROM EMPLOYEES WHERE JOBTITLE = 'PRESIDENT' --SELECAO BASEADA EM CRITERIOS

SELECT FIRSTNAME AS NOME, LASTNAME AS SOBRENOME, EMAIL, JOBTITLE AS CARGO FROM EMPLOYEES WHERE JOBTITLE = 'SALES REP'

SELECT FIRSTNAME AS NOME, LASTNAME AS SOBRENOME, EMAIL, JOBTITLE AS CARGO FROM EMPLOYEES WHERE JOBTITLE LIKE 'PRESIDENT%' --SELECAO QUE CONTEM A STRING DEFINIDA NO CAMPO LIKE

SELECT FIRSTNAME AS NOME, LASTNAME AS SOBRENOME, EMAIL, JOBTITLE AS CARGO FROM EMPLOYEES WHERE JOBTITLE = 'SALES REP' OR JOBTITLE LIKE '%SALE MANAGER%'

SELECT DISTINCT (FIRSTNAME), LASTNAME FROM EMPLOYEES --SELECAO QUE ELIMINA DUPLICIDADE

SELECT PRODUCTNAME, BUYPRICE, BUYPRICE * 1.20 AS SALEPRICE FROM PRODUCTS --SELECAO DE MULTIPLICACAO

SELECT PRODUCTNAME, BUYPRICE, BUYPRICE * QUANTITYINSTOCK FROM PRODUCTS

SELECT PRODUCTNAME, BUYPRICE, QUANTITYINSTOCK FROM PRODUCTS WHERE BUYPRICE > 90 AND BUYPRICE < 100 --BETWEEN EM COMPO LOGICO

SELECT PRODUCTNAME, BUYPRICE, QUANTITYINSTOCK FROM PRODUCTS WHERE BUYPRICE BETWEEN 90 AND 100 

SELECT PRODUCTNAME, BUYPRICE, BUYPRICE, QUANTITYINSTOCK FROM PRODUCTS WHERE BUY PRICE > 10.00 ORDER BY PRODUCTNAME ASC --SELECT EM ORDECAO PADRAO EM ASCENDENTE, OU DESC EM DESCENDENTE

SELECT PRODUCTNAME, BUYPRICE, BUYPRICE, QUANTITYINSTOCK FROM PRODUCTS ORDER BY QUANTITYINSTOCK, BUYPRICE DESC

SELECT * FROM EMPLOYEES WHERE OFFICECODE IN(1,2,4) --SELECAO EM QUE RETORNA OS REGISTROS NO CAMPO OFFICE ENTRE 1, 2 E 4

SELECT * FROM EMPLOYEES WHERE REPORTSTO IS NULL --OU IS NOT NULL 

