SELECT  NM_FUNCIONARIO AS NOME, DT_CADASTRAMENTO AS DATAADMISSAO FROM DB_FUNCIONARIO

SELECT * FROM DB_FUNCIONARIO

SELECT NM_FUNCIONARIO AS NOME, VL_SALARIO_BRUTO, VL_SALARIO_BRUTO * 1.05 AS PROJECAO_5, VL_SALARIO_BRUTO * 1.08 AS PROJECAO_8 FROM DB_FUNCIONARIO

SELECT * FROM DB_CLIENTE

SELECT NM_CLIENTE AS NOME, QT_ESTRELAS AS ESTRELAS FROM DB_CLIENTE

SELECT * FROM DB_PRODUTO

SELECT DS_PRODUTO AS DESCRITIVO_PRODUTO, VL_UNITARIO FROM DB_PRODUTO

SELECT * FROM DB_CLIENTE WHERE QT_ESTRELAS >= 4

SELECT * FROM DB_CLIENTE WHERE QT_ESTRELAS >= 3 AND VL_MEDIO_COMPRA > 70.00

SELECT NM_CLIENTE AS NOME, QT_ESTRELAS AS ESTRELAS, VL_MEDIO_COMPRA FROM DB_CLIENTE WHERE VL_MEDIO_COMPRA > 80.00

SELECT * FROM DB_PRODUTO WHERE VL_UNITARIO > 30.00

SELECT * FROM DB_PEDIDO WHERE EXTRACT (YEAR FROM DT_PEDIDO) = 2020 AND EXTRACT (MONTH FROM DT_PEDIDO) IN (1,2,4)

SELECT * FROM DB_FUNCIONARIO WHERE EXTRACT(MONTH FROM DT_CADASTRAMENTO) IN (11,12)

SELECT * FROM DB_PEDIDO WHERE DT_PEDIDO BETWEEN '01-01-2018' AND '31-12-2018'